### ISSUE TITLE
Viewer Render problem

### ISSUE THREAD

**Issue by mhmtyasr** [reearth/resium#647] opened 2023-12-01 10:04 UTC
Viewer is adding the map to the screen twice, what is the reason?
![Ekran görüntüsü 2023-12-01 130225](https://github.com/reearth/resium/assets/37835086/600ebd11-a112-4dde-afed-269188661721)
![Ekran görüntüsü 2023-12-01 130337s](https://github.com/reearth/resium/assets/37835086/ba2ba3bd-9628-454e-bc6d-3db27ee4f981)

**Comment by densgidley** [comment] 2023-12-04 17:35
This is caused by Vite hot reloading module.
For some odd reason, Vite still injects HMR code into the site even with it disabled.

I haven't able to find a temporary fix for this yet...

**Comment by wxmann** [comment] 2023-12-05 17:27
Try disabling React strict mode.

**Closed** 2023-12-07 19:46 UTC

**Comment by Skippou** [comment] 2023-12-07 20:21
Disabling React strict mode should not be the solution, especially for Resium.

From the docs: "<StrictMode> lets you find common bugs in your components early during development."

@wxmann @mhmtyasr

**Comment by olivermt** [comment] 2024-03-28 20:48
Could we maybe get this issue reopened?
I have the same issue.

![image](https://github.com/reearth/resium/assets/737765/cfe16bb5-bc34-4571-a664-1d9453e9572f)

Should maybe update the text here if it is indeed Vite HMR that causes this 😅 
StrictMode is made specifically to catch stuff like this, so disabling it is like saying to just delete your test if it fails.
